# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'assets/home.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomePage(object):
    def setupUi(self, HomePage):
        HomePage.setObjectName("HomePage")
        HomePage.resize(462, 292)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(HomePage.sizePolicy().hasHeightForWidth())
        HomePage.setSizePolicy(sizePolicy)
        HomePage.setStyleSheet("")
        self.verticalLayout = QtWidgets.QVBoxLayout(HomePage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(HomePage)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(20, 235, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(HomePage)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(HomePage)
        QtCore.QMetaObject.connectSlotsByName(HomePage)

    def retranslateUi(self, HomePage):
        _translate = QtCore.QCoreApplication.translate
        HomePage.setWindowTitle(_translate("HomePage", "HomePage"))
        self.label.setText(_translate("HomePage", "HOME PAGE"))
        self.label_2.setText(_translate("HomePage", "<html><head/><body><p align=\"center\">Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p><p align=\"center\">Donec vel orci id metus pellentesque commodo.</p><p align=\"center\">Aenean sed ante eget tortor pretium ullamcorper.</p><p align=\"center\">Curabitur malesuada turpis feugiat, ullamcorper eros non, fringilla sapien.</p><p align=\"center\">Proin convallis nulla quis pharetra consectetur.</p><p align=\"center\">In non mi placerat, tincidunt nunc sit amet, imperdiet libero.</p><p align=\"center\">Curabitur sed risus scelerisque, aliquam orci non, tincidunt elit.</p></body></html>"))
